Install Go 1.16 in our GitHub Actions workflow
This updates to use Go 1.16. This is to resolve the following error observed
in the lint job of our GitHub Actions workflow:

Error: ../../../go/pkg/mod/github.com/terraform-docs/terraform-docs@v0.12.0/internal/format/asciidoc_document.go:14:2: package embed is not in GOROOT (/opt/hostedtoolcache/go/1.15.10/x64/src/embed)